import random

ADJECTIVES = [
    "agile", "ancient", "arctic", "autumn", "azure", "basic", "bionic", "blue", "bold",
    "brave", "brisk", "bronze", "calm", "carbon", "chief", "arctic", "classic",
    "clear", "clever", "cold", "cool", "cosmic", "crimson", "cubic", "cyber",
    "daily", "dancing", "dapper", "dawn", "deep", "delta", "divine", "dream",
    "dynamic", "electric", "emerald", "epic", "eternal", "exotic", "expert",
    "fast", "final", "first", "fluent", "flying", "forest", "free", "frozen",
    "fusion", "future", "gala", "gallant", "gateway", "gentle", "giant", "gilded",
    "glass", "golden", "grand", "gray", "great", "green", "happy", "hidden",
    "holy", "honest", "humble", "hydro", "ice", "imperial", "indigo", "iron",
    "jade", "jet", "jovial", "jungle", "keen", "kinetic", "lunar", "magic",
    "major", "marine", "master", "mecha", "metal", "micro", "misty", "mobile",
    "modern", "molten", "motor", "mythic", "nano", "naval", "neon", "new", "noble",
    "lunar", "ocean", "omega", "onyx", "oracle", "orange", "orbital", "origin",
    "pale", "paper", "pearl", "penta", "pioneer", "primal", "prime", "promo",
    "proud", "pyro", "quantum", "quarter", "radiant", "river", "regal", "retro",
    "rising", "royal", "ruby", "sacred", "sapphire", "savvy", "scarlet", "secret",
    "serene", "shadow", "silent", "silver", "solar", "solid", "space", "spark",
    "steel", "stellar", "stone", "storm", "stray", "super", "tera", "terra",
    "tidal", "titan", "toxic", "triple", "turbo", "ultra", "urban", "valiant",
    "velvet", "video", "vivid", "white", "winter", "wise", "wonder", "yellow", "zen"
]

NOUNS = [
    "admiral", "agent", "alliance", "anchor", "apex", "armor", "arrow", "aspect",
    "avatar", "axis", "badger", "band", "bay", "beam", "blade", "blaze", "blitz",
    "blossom", "bolt", "bomb", "bond", "bot", "boulder", "bow", "breaker", "breeze",
    "brigade", "brook", "bullet", "burn", "cache", "cadet", "cannon", "capital",
    "captain", "cargo", "case", "castle", "catalyst", "cat", "cell", "center",
    "chain", "champion", "channel", "charm", "chimera", "chip", "circuit", "citadel",
    "claw", "cloud", "club", "cluster", "cobra", "code", "colonel", "colony",
    "comet", "command", "complex", "core", "cougar", "craft", "crest", "crew",
    "cross", "crown", "cruiser", "crush", "crystal", "current", "cyclone", "dagger",
    "dash", "dawn", "day", "delta", "demon", "depot", "depth", "design", "device",
    "digit", "dimension", "division", "dock", "doctor", "dog", "domain", "dragon",
    "drift", "drone", "drop", "dusk", "dynamic", "dynasty", "echo", "edge", "element",
    "elite", "elixir", "ember", "emblem", "empire", "engine", "enigma", "envoy",
    "epoch", "era", "essence", "eternity", "expanse", "expedition", "expert", "eye",
    "factor", "falcon", "fang", "fault", "fauna", "field", "fire", "fist", "flame",
    "flare", "fleet", "flow", "flux", "focus", "force", "forest", "forge", "formula",
    "fortress", "fossil", "fox", "frame", "freedom", "front", "frost", "fury",

    "fusion", "gadget", "galleon", "game", "gate", "gauntlet", "gear", "gem",
    "general", "genesis", "giant", "gift", "glacier", "glory", "goliath", "grace",
    "grain", "griffin", "grid", "group", "grove", "guard", "guardian", "guild",
    "gun", "hadron", "hammer", "hand", "harbor", "hawk", "haze", "heart", "helix",
    "helmet", "hero", "hive", "horizon", "horn", "horse", "hound", "hour", "hunter",
    "hydra", "ice", "icon", "inferno", "infinity", "island", "ivory", "jackal",
    "jade", "jaw", "jet", "jewel", "journey", "judge", "jungle", "keeper", "key",
    "khan", "king", "knight", "kraken", "lagoon", "lake", "lance", "laser", "leaf",
    "league", "legion", "lens", "leopard", "level", "lever", "light", "limit",
    "link", "lion", "locus", "logic", "lord", "machine", "magma", "major", "manifest",
    "map", "marine", "mark", "marshal", "mask", "master", "matrix", "matter",
    "maze", "mechanic", "memory", "mercury", "mesh", "meta", "meteor", "might",
    "mile", "mind", "mirage", "missile", "mission", "mist", "model", "mole",
    "monarch", "monitor", "monster", "moon", "morph", "motion", "mountain", "myth",
    "nano", "nation", "needle", "nemesis", "neptune", "net", "network", "nexus",
    "night", "nova", "nucleus", "number", "nymph", "oasis", "object", "obsidian",
    "ocean", "omega", "omen", "onyx", "operator", "oracle", "orb", "orbit", "order",

    "origin", "ouroboros", "outpost", "page", "paladin", "pandora", "panel", "panic",
    "panther", "paradigm", "paradox", "particle", "path", "pattern", "pegasus",
    "pendant", "pendulum", "phantom", "phenomenon", "phoenix", "pillar", "pilot",
    "pin", "pioneer", "pipe", "pirate", "pit", "pivot", "pixel", "plane", "planet",
    "plasma", "platoon", "pod", "point", "poly", "pool", "portal", "power", "pride",
    "prince", "prism", "prodigy", "program", "project", "prophecy", "prophet",

    "protocol", "proxy", "pulse", "punch", "puzzle", "pyramid", "python", "quantum",
    "quarter", "quasar", "quest", "radiant", "rage", "raider", "rail", "ram",
    "ranger", "ray", "reactor", "realm", "reaper", "relic", "renegade", "replica",
    "reset", "resonance", "resonator", "riddle", "rift", "ring", "ritual", "river",
    "road", "robot", "rock", "rogue", "rose", "rotor", "rover", "ruby", "ruin",
    "rune", "saber", "saga", "saint", "sanctuary", "sapphire", "savage", "scale",
    "scarab", "scar", "scepter", "scheme", "scholar", "scope", "scorpion", "scout",
    "script", "scythe", "sea", "seal", "search", "secret", "sector", "seed", "seer",
    "serpent", "server", "shadow", "shaft", "shard", "shell", "shield", "ship",
    "shroud", "signal", "silver", "siren", "skull", "sky", "slave", "slayer",
    "sling", "snake", "snow", "solar", "soldier", "solstice", "song", "sorcerer",
    "soul", "source", "space", "spark", "specter", "spectrum", "sphere", "sphinx",
    "spider", "spike", "spire", "spirit", "spore", "spring", "squad", "squire",
    "staff", "stage", "star", "state", "status", "steel", "stinger", "stone",
    "storm", "story", "strand", "stream", "strike", "striker", "string", "stronghold",
    "sun", "surge", "swarm", "sword", "symbol", "syndicate", "synergy", "system",
    "talisman", "talon", "tank", "target", "task", "team", "tear", "tech", "temper",
    "tempest", "temple", "tempo", "tendril", "tentacle", "terra", "terror", "thorn",
    "thought", "thunder", "tiger", "time", "titan", "token", "tome", "tool", "topaz",
    "torch", "torment", "torpedo", "torrent", "totem", "tower", "trace", "track",
    "trader", "trail", "train", "trap", "traveler", "treaty", "tree", "tribe",
    "trident", "trigger", "trinity", "triumph", "troll", "trooper", "trophy", "tundra",
    "tunnel", "twin", "typhoon", "unit", "universe", "urn", "vanguard", "vector",
    "veil", "venom", "venture", "vermin", "vessel", "vestige", "vibration", "victory",
    "viper", "vision", "visitor", "void", "volcano", "volume", "vortex", "voyage",
    "vulture", "wall", "wanderer", "warden", "warfare", "warg", "warrior", "wasp",
    "watch", "watcher", "wave", "weapon", "web", "wheel", "whip", "whirlwind", "wind",
    "wing", "winter", "wire", "wish", "witch", "wizard", "wolf", "word", "world",
    "worm", "wraith", "wreck", "wyrm", "wyvern", "year", "yellow", "zenith", "zephyr",
    "zero", "zone"
]


def generate_name() -> str:
    """Generates a random 'adjective-noun' name."""
    adjective = random.choice(ADJECTIVES)
    noun = random.choice(NOUNS)
    return f"{adjective}-{noun}"
